apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"hytis:staging","namespace":"ohtuprojekti-staging"},"fieldPath":"spec.template.spec.containers[?(@.name==\"hytis\")].image","pause":"false"}]
  name: hytis-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hytis
  template:
    metadata:
      labels:
        app: hytis
    spec:
      containers:
        - name: hytis
          image: hytis:staging
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          envFrom:
            - configMapRef:
                name: hytis-config


