apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"sijoittaja:staging","namespace":"ohtuprojekti-staging"},"fieldPath":"spec.template.spec.containers[?(@.name==\"sijoittaja-frontend\")].image","pause":"false"}]
  name: sijoittaja-frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sijoittaja-frontend
  template:
    metadata:
      labels:
        app: sijoittaja-frontend
    spec:
      containers:
        - name: sijoittaja-frontend
          image: sijoittaja-frontend:staging
          ports:
            - containerPort: 4173
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "50Mi"
              cpu: "50m"

