kind: ImageStream
apiVersion: image.openshift.io/v1

metadata:
  name: sijoittaja-backend
  labels:
    app: sijoittaja-backend
spec:
  lookupPolicy:
    local: false
  tags:
    - name: staging
      from:
        kind: DockerImage
        name: l0uko/sijoittaja-backend:staging
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local