kind: ImageStream
apiVersion: image.openshift.io/v1

metadata:
  name: hytis
  labels:
    app: hytis
spec:
  lookupPolicy:
    local: false
  tags:
    - name: staging
      from:
        kind: DockerImage
        name: ghcr.io/hytis-ohtu/hytis:staging
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local