#currently copied from materials, placeholder values
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: sijoittaja-svc
#spec:
#  type: NodePort
#  selector:
#    app: sijoittaja
#  ports:
#    - name: http
#      nodePort: 30080
#      protocol: TCP
#      port: 1234
#      targetPort: 3000
#