apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sijoittaja-route
  namespace: ohtuprojekti-staging
  labels:
    app: sijoittaja
    type: external
spec:
  host: ohtuprojekti-staging.ext.ocp-test-0.k8s.it.helsinki.fi 
  port:
    targetPort: 4173
  to:
    kind: Service
    name: sijoittaja-svc
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None