apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hytis-route
  namespace: ohtuprojekti-staging
  labels:
    app: hytis
    type: external
spec:
  host: hytis-ohtuprojekti-staging.ext.ocp-test-0.k8s.it.helsinki.fi
  port:
    targetPort: 3000
  to:
    kind: Service
    name: hytis-svc
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None