#currently copied from materials, placeholder values

# Let us create a file service.yaml into the manifests folder.
#  We need the service to do the following things:

#  Declare that we want a Service
#  Declare which port to listen to
#  Declare the application where the request should be directed to
#  Declare the port where the request should be directed to

#The following service.yaml definition will let TCP traffic from port 2345 to port 3000:
apiVersion: v1
kind: Service
metadata:
  name: sijoittaja-svc
spec:
  type: NodePort
  selector:
    app: sijoittaja # This is the app as declared in the deployment.
  ports:
    - name: http
      nodePort: 39053 # This is the port that is available outside. Value for nodePort can be between 30000-32767
      protocol: TCP
      port: 1234 # This is a port that is available to the cluster, in this case it can be ~ anything
      targetPort: 4173 # This is the target port