name: "CI/CD pipeline"

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
    uses: ./.github/workflows/frontend.yaml

  backend:
    uses: ./.github/workflows/backend.yaml
    secrets:
      SECRET: ${{ secrets.SECRET }}

  build-and-push-dev:
    if: |
      always()
      && github.ref == 'refs/heads/dev'
    needs: [frontend, backend]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #- name: Setup buildx
      #  uses: docker/setup-buildx-action@v3
      #- name: Build and push
      #  uses: docker/build-push-action@v6
      #  with:
      #    push: true
      #    tags: |
      #      ghcr.io/OhTu-Tilasijoittelujarjestelma/hytis:staging
      #      ghcr.io/OhTu-Tilasijoittelujarjestelma/hytis:${{ github.sha }}
      #    #cache-from: type=registry,ref=ghcr.io/OhTu-Tilasijoittelujarjestelma/hytis:buildcache
      #    #cache-to: type=registry,ref=ghcr.io/OhTu-Tilasijoittelujarjestelma/hytis:buildcache,mode=max
      #    build-args: EXPO_PUBLIC_SOCKET_URL_WEB_ARG=https://hytis-ohtuprojekti-staging.ext.ocp-test-0.k8s.it.helsinki.fi
#
  #build-and-push-prod:
  #  if: |
  #    always()
  #    && github.ref == 'refs/heads/main'
  #  needs: [frontend, backend]
  #  runs-on: ubuntu-24.04
  #  permissions:
  #    contents: read
  #    packages: write
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: log in to ghcr
  #      uses: docker/login-action@v3
  #      with:
  #        registry: ghcr.io
  #        username: ${{ github.actor }}
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    - name: Setup buildx
  #      uses: docker/setup-buildx-action@v3
  #    - name: Build and push
  #      uses: docker/build-push-action@v6
  #      with:
  #        push: true
  #        tags: |
  #          ghcr.io/OhTu-Tilasijoittelujarjestelma/hytis:prod
  #          ghcr.io/OhTu-Tilasijoittelujarjestelma/hytis:${{ github.sha }}
  #        cache-from: type=registry,ref=ghcr.io/OhTu-Tilasijoittelujarjestelma/hytis:prodbuildcache
  #        cache-to: type=registry,ref=ghcr.io/OhTu-Tilasijoittelujarjestelma/hytis:prodbuildcache,mode=max
  #        #build-args: EXPO_PUBLIC_SOCKET_URL_WEB_ARG=https://hytis-ohtuprojekti-staging.ext.ocp-prod-0.k8s.it.helsinki.fi
