name: "CI/CD pipeline"

on:
  push:
    branches:
      - main
      - dev
    #paths: This braks the file. I dont know why
    #  - 'frontend/**'
    #  - 'backend/**'
  pull_request:
    branches:
      - 'main'
      - 'dev'
    #paths:
    #  - 'frontend/**'
    #  - 'backend/**'

jobs:
  frontend:
    uses: ./.github/workflows/frontend.yaml

  backend:
    uses: ./.github/workflows/backend.yaml
    secrets:
      SECRET: ${{ secrets.SECRET }}

  build-and-push-dev:
    if: |
      always()
      && github.ref == 'refs/heads/dev'
    needs: [frontend, backend]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          context: .
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/hytis-ohtu/hytis:staging
            ghcr.io/hytis-ohtu/hytis:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/hytis-ohtu/hytis:buildcache
          cache-to: type=registry,ref=ghcr.io/hytis-ohtu/hytis:buildcache,mode=max
